config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  get 'welcome/index'

  resources :users, only: [:edit, :update, :show] do
    resources :fields, only: [] do
      delete ':resource/:key', to: 'fields#destroy', as: :delete, on: :collection
      get ':resource/new', to: 'fields#new', as: :new, on: :collection
      post ':resource', to: 'fields#create', as: :create, on: :collection
      get ':resource/:key/edit', to: 'fields#edit', as: :edit, on: :collection
      put ':resource/:key', to: 'fields#update', as: :update, on: :collection
    end
    resources :people, except: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field
  include ActiveModel::Validations
  include ActiveModel::Conversion

  attr_accessor :name, :type, :key, :is_filter_exist, :is_sort_exist

  validates_presence_of :name, :type
  validates_inclusion_of :type, in: %w(number text)

  def initialize(attributes = {})
    self.is_filter_exist = false
    self.is_sort_exist = false
    attributes.each do |name, value|
      if name.in?(%w(is_filter_exist is_sort_exist))
        value = value.to_s.in?( %w(1 true) )
      end
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def validate_key
    validates_length_of :key, maximum: 100
    validates_presence_of :key
  end

  def key_parameterize
    self.key = self.key.parameterize.underscore if self.key.present?
  end

  def as_json
      {
          name: name,
          type: type,
          is_filter_exist: is_filter_exist,
          is_sort_exist: is_sort_exist
      }
  end
end

app/models/person.rb
class Person < ApplicationRecord

  validates_presence_of :name, :surname

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  before_action :set_user
  before_action :set_resource
  before_action :set_key, only: [:edit, :update, :destroy]

  def new
    @field = Field.new
  end

  def create
    @field = Field.new(params_field)
    @field.key_parameterize
    @field.valid?
    @field.validate_key
    unless @field.errors.any?
      @user.fields[@resource][@field.key] = @field.as_json
      @user.save
      flash[:success] = 'Field added successfully'
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid field parameters!'
      render :new
    end
  end

  def edit
    @field = Field.new(@user.fields[@resource][@key])
    @field.key = @key
  end

  def update
    @field = Field.new(params_field)
    if @field.valid?
      @user.fields[@resource][@key] = @field.as_json
      @user.save
      flash[:success] = 'Field updated successfully'
      redirect_to @user
    else
      @field.errors.delete(:key)
      flash.now[:danger] = 'Invalid field parameters!'
      @field.key = @key
      render :edit
    end
  end

  def destroy
    @user.fields[@resource].delete(@key) if @user.fields[@resource].present?
    @user.save
    flash[:success] = 'Field destroyed successfully'
    redirect_to @user
  end

  private

    def params_field
      params.require(:field).permit(:key, :name, :type, :is_filter_exist, :is_sort_exist)
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_resource
      @resource = params[:resource]
    end

    def set_key
      @key = params[:key]
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :set_user
  before_action :set_fields
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.metadata = person_metadata_params
    if @person.save
      flash[:success] = 'Person created successfully'
      redirect_to user_person_path(@user, @person)
    else
      flash.now[:danger] = 'Invalid person parameters!'
      render :new
    end
  end

  def edit
  end

  def update
    @person.metadata = person_metadata_params
    if @person.update(person_params)
      flash[:success] = 'Person updated successfully'
      redirect_to user_person_path(@user, @person)
    else
      flash.now[:danger] = 'Invalid person parameters!'
      render :edit
    end
  end

  def show
  end

  def destroy
    @person.destroy
    flash[:success] = 'Person destroyed successfully'
    redirect_to @user
  end

  private

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_person
      @person = Person.find(params[:id])
    end

    def set_fields
      @fields = @user.fields['person']
    end

    def person_params
      params.require(:person).permit(:name, :surname, :age, :email)
    end

    def person_metadata_params
      parameters = @fields.keys
      params.require(:person).permit(parameters).to_hash
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :set_person_ransackers, only: :show

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user
  end

  def show
    @search = Person.search(params[:q])
    @people = @search.result
  end

  private

    def user_params
      params.require(:user).permit(:name)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_person_ransackers
      @fields = @user.fields['person']
      return unless @fields.present?
      @fields.keys.each do |key|
        ransack_help(key)
      end
    end

    def ransack_help(type)
      Person.class_eval do
        Rails.logger.warn "Ransacker initialized for #{type.upcase}".red
        ransacker "metadata_#{type}".to_sym do |parent|
          Arel::Nodes::InfixOperation.new('->>', parent.table[:metadata], Arel::Nodes.build_quoted(type))
        end
      end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fields/_common_fields.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :type %>
  <%= f.select :type, [['Number', 'number'], ['Text', 'text']],  {}, { class: 'form-control'} %>
</div>

<div class="checkbox">
  <label>
    <%= f.check_box :is_filter_exist %>
    Show filter?
  </label>
</div>

<div class="checkbox">
  <label>
    <%= f.check_box :is_sort_exist %>
    Show sort link?
  </label>
</div>

app/views/fields/_field_errors.html.erb
<% if @field.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(@field.errors.count, 'error') %>
          prohiited this field from being saved:
        </h2>
      </div>

      <div class="panel-body">
        <ul>
          <% @field.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/fields/edit.html.erb
<%= render 'shared/user_link'%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      <%= @resource.camelize %>
      Fields Edit
    </h3>
  </div>
  <div class="panel-body">

    <%= form_for @field, url: update_user_fields_path(@user, @resource, @key), method: :put do |f| %>
        <%= render 'field_errors'%>

        <div class="form-group">
          <%= f.label :key %>
          <%= f.text_field :key, class: 'form-control', disabled: :disabled  %>
        </div>

        <%= render 'common_fields', f: f %>

        <div class="form-group">
          <%= f.submit class: 'btn btn-primary', value: 'Update Field'%>
          <%= link_to 'Back', :back, class: 'btn btn-default'%>
        </div>
    <% end %>
  </div>
</div>

app/views/fields/new.html.erb
<%= render 'shared/user_link'%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      <%= @resource.camelize %>
      Field Add
    </h3>
  </div>
  <div class="panel-body">

    <%= form_for @field, url: create_user_fields_path(@user, @resource) do |f| %>
        <%= render 'field_errors'%>

        <div class="form-group">
          <%= f.label :key %>
          <%= f.text_field :key, class: 'form-control' %>
        </div>

        <%= render 'common_fields', f: f %>

        <div class="form-group">
          <%= f.submit class: 'btn btn-primary'%>
          <%= link_to 'Back', :back, class: 'btn btn-default'%>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostgreSQL Jsonb Ransack Rails 5</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render 'shared/header' %>

        <%= render 'shared/message'%>
        <%= yield %>

      </div>
    </div>
  </div>
  </body>
</html>

app/views/people/_common_fields.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :surname %>
  <%= f.text_field :surname, class: 'form-control' %>
</div>

<% if @fields.present? %>
    <% @fields.keys.each do |key| %>
        <div class="form-group">
          <div class="form-group">
            <label for="person_<%= key %>"><%= @fields[key]['name'] %></label>
            <input class="form-control" type="<%= @fields[key]['type'] %>" name="person[<%= key %>]" value="<%= @person.metadata[key] %>" id="person_<%= key %>">
          </div>
        </div>
    <% end %>
<% end %>

app/views/people/_field_errors.html.erb
<% if @person.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(@person.errors.count, 'error') %>
          prohiited this person from being saved:
        </h2>
      </div>

      <div class="panel-body">
        <ul>
          <% @person.errors.full_messages.each do |message| %>
              <li>
                <%= message %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/people/edit.html.erb
<%= render 'shared/user_link'%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      Person Edit
    </h3>
  </div>
  <div class="panel-body">

    <%= form_for @person, url: user_person_path(@user, @person) do |f| %>
        <%= render 'field_errors'%>

        <%= render 'common_fields', f: f %>

        <div class="form-group">
          <%= f.submit class: 'btn btn-primary'%>
          <%= link_to 'Back', :back, class: 'btn btn-default'%>
        </div>
    <% end %>
  </div>
</div>

app/views/people/new.html.erb
<%= render 'shared/user_link'%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      Person Add
    </h3>
  </div>
  <div class="panel-body">

    <%= form_for @person, url: user_people_path(@user) do |f| %>
        <%= render 'field_errors'%>

        <%= render 'common_fields', f: f %>

        <div class="form-group">
          <%= f.submit class: 'btn btn-primary'%>
          <%= link_to 'Back', :back, class: 'btn btn-default'%>
        </div>
    <% end %>
  </div>
</div>

app/views/people/show.html.erb
<%= render 'shared/user_link'%>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      Person Detail
    </h3>
  </div>
  <div class="panel-body">
    <strong>Name</strong>: <%= @person.name %>
    <br/>
    <strong>Surname</strong>: <%= @person.surname %>
    <br/>
    <% @person.metadata.each do |k, v| %>
      <strong><%= @fields[k]['name'] %></strong>: <%= v %>
      <br/>
    <% end %>
    <hr/>
    <%= link_to 'Edit', edit_user_person_path(@user, @person) %>
    <%= link_to 'Delete', user_person_path(@user, @person), method: :delete %>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">PostgreSQL Jsonb Custom Field with Ransack</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'Users', root_path %> </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_message.html.erb
<% flash.each do |key, message| %>
  <div class="text-center alert alert-<%= key.in?(%w(notice success))  ? 'success' : 'danger' %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_user_link.html.erb
<h2 class="text-center">
  <%= link_to @user.name, user_path(@user) %>
  <span style="font-size: 13px;">
    <%= link_to 'Edit', edit_user_path(@user) %>
  </span>
</h2>

app/views/users/_common.html.erb
<%= render 'shared/user_link'%>

<%= render 'users/fields', user: @user, fields: @fields, resource: 'person' %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        People List
        <div class="pull-right">
          <%= link_to 'New', new_user_person_path(@user) %>
        </div>
      </div>
      <div class="panel-body">
        <% if @fields.present? %>
            <%= search_form_for @search, url: user_path(@user), html: { class: 'form-inline'} do |f| %>
                <% @fields.keys.each do |key| %>
                    <% if @fields[key]['is_filter_exist'] %>
                        <div class="form-group">
                          <%= f.label @fields[key]['name'] %>
                          <%= f.search_field "metadata_#{key}_cont", class: 'form-control' %>
                        </div>
                    <% end %>
                <% end %>
                <%= f.submit class: 'btn btn-primary' %>
            <% end %>
            <br/>
        <% end %>
        <table class="table table-hover table-striped">
          <tr>
            <th><%= sort_link(@search, :id, 'ID', default_order: :desc) %></th>
            <th><%= sort_link(@search, :name, 'Name', default_order: :desc) %></th>
            <% if @fields.present? %>
                <% @fields.keys.each do |key| %>
                    <th>
                      <%  if @fields[key]['is_sort_exist'] %>
                          <%= sort_link(@search, "metadata_#{key}", @fields[key]['name'], default_order: :desc) %>
                      <% else %>
                          <%= @fields[key]['name'] %>
                      <% end %>
                    </th>
                <% end %>
            <% end %>
            <th>Actions</th>
          </tr>
          <% @people.each do |person| %>
              <tr>
                <td><%= person.id %></td>
                <td><%= person.name %></td>
                <% if @fields.present? %>
                    <% @fields.keys.each do |key| %>
                        <td><%= person.metadata[key] %></td>
                    <% end %>
                <% end %>
                <td>
                  <%= link_to 'Show', user_person_path(@user, person) %>
                  <%= link_to 'Edit', edit_user_person_path(@user, person) %>
                  <%= link_to 'Delete', user_person_path(@user, person), method: :delete %>
                </td>
              </tr>
          <% end %>
        </table>
      </div>
      <div class="panel-footer">
        People count:
        <%= @people.count %>
      </div>
    </div>
  </div>
</div>

app/views/users/_fields.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    User fields
    <div class="pull-right">
      <%= link_to 'New', new_user_fields_path(user, resource) %>
    </div>
  </div>
  <div class="panel-body">
    <% if fields.present? %>
            <% fields.keys.each do |key| %>
                <span class="well" style="float: left; margin: 0px 5px 10px; padding: 10px;">
                  <label><%= fields[key]['name'] %></label>
                  <ul>
                    <li>Type: <%= fields[key]['type'] %></li>
                    <li>Filter : <%= fields[key]['is_filter_exist'] ? 'Yes' : 'No' %></li>
                    <li>Sort link : <%= fields[key]['is_sort_exist'] ? 'Yes' : 'No' %></li>
                  </ul>
                  <%= link_to 'Delete', delete_user_fields_path(user, resource, key), method: :delete %>
                  <%= link_to 'Edit', edit_user_fields_path(user, resource, key) %>
                </span>
            <% end %>
    <% else %>
        <%= link_to 'Add new field', new_user_fields_path(user, resource) %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      <%= @user.name %>
      Edit
    </h3>
  </div>
  <div class="panel-body">
    <%= form_for @user do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control'  %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Back', :back, class: 'btn btn-default'%>
      </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'users/common' %>

app/views/welcome/_common.html.erb
<%= link_to 'Welcome', welcome_index_path %>
<br/>
<br/>
<% if @fields.present? %>
  User fields :
  <ul>
    <% @fields.keys.each do |key| %>
        <li>
          <%= @fields[key]['name'] %>
          <ul>
            <li>Is sort exists: <%= @fields[key]['is_sort_exist'] %></li>
            <li>Is filter exists: <%= @fields[key]['is_filter_exist'] %></li>
            <li>Type: <%= @fields[key]['type'] %></li>
          </ul>
        </li>
    <% end %>
  </ul>
<% end %>
<%= link_to 'Edit', edit_user_path(@user) %>
<br/>
<br/>
<% if @fields.present? %>
  Contains :
  <%= search_form_for @search, url: user_path(@user) do |f| %>
    <% @fields.keys.each do |key| %>
      <% if @fields[key]['is_filter_exist'] %>
        <%= f.label @fields[key]['name'] %>
        <%= f.search_field "metadata_#{key}_cont" %>
      <% end %>
    <% end %>
    <%= f.submit %>
  <% end %>
  <br/>
<% end %>
<hr/>
<table>
  <tr>
    <th><%= sort_link(@search, :id, 'ID', default_order: :desc) %></th>
    <% if @fields.present? %>
      <% @fields.keys.each do |key| %>
          <th>
            <%  if @fields[key]['is_sort_exist'] %>
              <%= sort_link(@search, "metadata_#{key}", @fields[key]['name'], default_order: :desc) %>
            <% else %>
                <%= @fields[key]['name'] %>
            <% end %>
          </th>
      <% end %>
    <% end %>
  </tr>
  <% @people.each do |d| %>
    <tr>
      <td><%= d.id %></td>
      <% if @fields.present? %>
        <% @fields.keys.each do |key| %>
            <td><%= d.metadata[key] %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>

</table>
<hr/>
People count:
<%= @people.count %>

app/views/welcome/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      Users List
    </h3>
  </div>
  <div class="panel-body">
    <ul>
      <% @users.each do |user| %>
          <li><%= link_to user.name, user_path(user) %></li>
      <% end %>
    </ul>
  </div>
</div>